# Generated by Django 4.0.4 on 2022-04-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameofbook', models.CharField(max_length=200)),
                ('statusofbook', models.CharField(max_length=200)),
                ('rollnoburrower', models.IntegerField()),
            ],
        ),
    ]
